name: Node.js CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Secret Length
        run: echo "PROD_ENV_FILE length ${#PROD_ENV_FILE}"
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}

      - name: Create .env file
        run: |
          touch .env
          printf "%s" "${{ secrets.PROD_ENV_FILE }}" > .env
          
      - run: yarn install --frozen-lockfile

      # Debugging: Check if the secret is available

      # Properly write the secret to the .env file (handles multiline secrets)

      # Verify that the .env file was created (remove or modify for security)
      - name: Verify .env file
        run: cat .env
      - name: Run prisma generate
        run: yarn run make:migration
      - name: Run build
        run: yarn run build
      - name: Run pm2 stop
        run: pm2 stop all
      - name: Run pm2 delete
        run: pm2 delete all
      - name: Run pm2 start
        run: yarn run start:prod
