name: Node.js CI

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --frozen-lockfile

      # Debugging: Check if the secret is available
      - name: Debug Secret Length
        run: echo "PROD_ENV_FILE length ${#PROD_ENV_FILE}"
        env:
          PROD_ENV_FILE: ${{ secrets.PROD_ENV_FILE }}

      # Properly write the secret to the .env file (handles multiline secrets)
      - name: Create .env file
        run: |
          touch .env
          printf "%s" "${{ secrets.PROD_ENV_FILE }}" > .env

      # Verify that the .env file was created (remove or modify for security)
      - name: Verify .env file
        run: cat .env
      - name: Run pm2 start
        run: yarn run start:prod
